{
  lib,
  config,
  ...
}:

with lib;

{
  services = {
    # INFO: default
    "winapps" = {
      serviceConfig = {
        Restart = mkOverride 90 "on-failure";
        RestartMaxDelaySec = mkOverride 90 "1m";
        RestartSec = mkOverride 90 "100ms";
        RestartSteps = mkOverride 90 9;
      };
    }
    // (genAttrs
      [
        "after"
        "requires"
        "upheldBy"
      ]
      (n: [
        "winapps_default.service"
        "winapps_data.service"
      ])
    )
    // (genAttrs
      [
        "partOf"
        "wantedBy"
      ]
      (n: [
        "docker-compose-winapps-root.target"
      ])
    );

    # INFO: volumes
    "winapps-data" = {
      path = [ config.virtualisation.podman.package ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        podman volume inspect winapps_data || podman volume create winapps_data
      '';

      partOf = [ "winapps-root.target" ];
      wantedBy = [ "winapps-root.target" ];
    };

    # INFO: network
    "winapps-network" = {
      path = [ config.virtualisation.podman.package ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f winapps_network";
      };

      script = ''
        podman network inspect winapps_network || podman network create winapps_network
      '';

      partOf = [ "winapps-root.target" ];
      wantedBy = [ "winapps-root.target" ];
    };
  };

  # INFO: root target
  targets."winapps-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };

    wantedBy = [ "multi-user.target" ];
  };
}
