{
  pkgs,
  lib,
  config,
  ...
}:

with lib;

# INFO
# 1) enable this module
# 2) wait for rebuild
# 3) watch 'systemctl status podman-winapps.service'
# 4) enter to http://localhost:8006
# 5) your windows is ready

mkIf false {
  persist.user.files = [ ".local/share/winapps/winapps.log" ];

  virtualisation.oci-containers.containers."winapps" = {
    image = "ghcr.io/dockur/windows:latest";

    environment =
      let
        mk = n: toString (8 * n);
      in
      {
        "VERSION" = "tiny11"; # INFO: low size lightweight win11
        "CPU_CORES" = mk 1;
        "RAM_SIZE" = mk 1 + "G";
        "DISK_SIZE" = mk 8 + "G";
        "HOME" = config.users.users.${system.userName}.home;
        "USERNAME" = system.userName;
        "PASSWORD" = "windows";
        GPU = "Y";
      };

    volumes = [
      "/home/${system.userName}:/shared:rw"
      "/media:/media:rw"
      "winapps_data:/storage:rw"
    ];

    devices = [
      "/dev/dri"
    ];

    ports = [
      "8006:8006/tcp"
      "3389:3389/tcp"
      "3389:3389/udp"
    ];

    log-driver = "journald";

    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/kvm:/dev/kvm:rwm"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network=winapps_network"
      "--network-alias=windows"
      "--privileged"
    ];
  };

  environment.systemPackages = with pkgs; [
    winapps
    winapps-launcher
  ];

  hm.xdg.configFile."winapps/winapps.conf".text = generators.toINIWithGlobalSection { } {
    globalSection = {
      RDP_USER = system.userName;
      RDP_PASS = "windows";
      RDP_DOMAIN = "wlfreerdp";

      RDP_IP = "127.0.0.1";
      WAFLAVOR = "podman";
      RDP_SCALE = "100";

      RDP_FLAGS = "\"/cert:tofu /sound /microphone\"";
      MULTIMON = "false";
      DEBUG = "true";

      AUTOPAUSE = "on";
      AUTOPAUSE_TIME = "300";
      FREERDP_COMMAND = "";
    };
    sections = { };
  };

  systemd = {
    services = {
      # INFO: default
      "winapps" =
        let
          dataNetwork = [
            "winapps_default.service"
            "winapps_data.service"
          ];

          root = [
            "docker-compose-winapps-root.target"
          ];
        in
        {
          serviceConfig = {
            Restart = mkOverride 90 "on-failure";
            RestartMaxDelaySec = mkOverride 90 "1m";
            RestartSec = mkOverride 90 "100ms";
            RestartSteps = mkOverride 90 9;
          };

          after = dataNetwork;
          partOf = root;
          requires = dataNetwork;
          upheldBy = dataNetwork;
          wantedBy = root;
        };

      # INFO: volumes
      "winapps-data" = {
        path = [ config.virtualisation.podman.package ];

        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };

        script = ''
          podman volume inspect winapps_data || podman volume create winapps_data
        '';

        partOf = [ "winapps-root.target" ];
        wantedBy = [ "winapps-root.target" ];
      };

      # INFO: network
      "winapps-network" = {
        path = [ config.virtualisation.podman.package ];

        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "docker network rm -f winapps_network";
        };

        script = ''
          podman network inspect winapps_network || podman network create winapps_network
        '';

        partOf = [ "winapps-root.target" ];
        wantedBy = [ "winapps-root.target" ];
      };
    };

    # INFO: root target
    targets."winapps-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };

      wantedBy = [ "multi-user.target" ];
    };
  };
}
