# reference
# https://github.com/eh8/chenglab/blob/main/.github/workflows/release.yml
# https://github.com/Frogging-Family/wine-tkg-git/blob/master/.github/workflows/proton-arch-ntsync-nopackage.yml

name: "Build and push nixos iso to releases"

on:
  # build on new release
  release:
    types: [created]

  # manually via "Actions" in github
  workflow_dispatch:

env:
  # nix config, substit. & keys for cache
  EXTRA_NIX_CONFIG: |
    auto-optimise-store = true
    download-buffer-size = 500000000
    experimental-features = nix-command flakes
    max-jobs = auto
    substituters = https://cache.garnix.io https://xache.cachix.org
    trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= xache.cachix.org-1:InoMKnvFvDh+J5gFNHN1mmUONxvYJqFImLJY8/bl9YA=

jobs:
  build:
    runs-on: ubuntu-latest # idk what ir means

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install NIX
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: ${{ env.EXTRA_NIX_CONFIG }}

      - name: Build
        run: |
          nix_bin=$(which nix) # idk why, lol
          sudo $nix_bin build .#iso
          # .#iso it is ~/packages/iso.nix
          # self.nixosConfigurations.isoXtended.config.system.build.isoImage
          # why isoXtended? idk im shizo hahahahahhaha

      - name: Rename
        run: sudo mv result/iso/*.iso nixos-minimal.iso

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-minimal
          path: nixos-minimal.iso

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: nixos-minimal.iso
