name: "Cleanup old workflows"

on:
  schedule:
    - cron: "0 0 * * *" # everyday at midnight

  workflow_dispatch: # manual

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Prune
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 14 # prune after 14 days
          keep_minimum_runs: 4
